#!/usr/bin/env python3
"""Pre-scale paintings to the same 2048 px limit used by the mobile renderer."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'public/assets'
SOURCES = [*ASSETS.glob('bg/**/*.webp'), *ASSETS.glob('intro/*.webp'), ASSETS / 'ui/title_bg.webp']
names = []
before = after = 0
for path in sorted(SOURCES):
    if path.stem.endswith('_m'):
        continue
    with Image.open(path) as im:
        if max(im.size) <= 2048:
            continue
        k = 2048 / max(im.size)
        scaled = im.resize((round(im.width * k), round(im.height * k)), Image.Resampling.LANCZOS)
        target = path.with_name(path.stem + '_m.webp')
        scaled.save(target, 'WEBP', quality=93, method=6, exact=True)
    names.append('assets/' + str(path.relative_to(ASSETS)))
    before += path.stat().st_size
    after += target.stat().st_size

out = ROOT / 'src/core/mobile_art.js'
out.write_text('// Generated by tools/build_mobile_art.py.\nexport const mobileArt = new Set(' + repr(names) + ');\n')
print(f'{len(names)} paintings: {before / 1048576:.2f} MiB -> {after / 1048576:.2f} MiB')
