#!/usr/bin/env python3
"""Bake the title logo's drip attachment and pigment lookup textures."""
import base64
import math
import random
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
im = Image.open(root / 'public/assets/ui/logo_clean.webp').convert('RGBA')
w, h = im.size
pix = im.load()
n = 256
edge = bytearray(n * 4)
color = bytearray(n * 4)
rng = random.Random(2026)
for col in range(n):
    x0, x1 = math.floor(col / n * w), math.floor((col + 1) / n * w)
    lowest, red = -1, 0
    for x in range(x0, x1):
        for y in range(h - 1, -1, -1):
            r, g, b, a = pix[x, y]
            if a > 200:
                if y > lowest:
                    lowest, red = y, (r - max(g, b)) / 255
                break
    edge[col * 4] = 0 if lowest < 0 else round(lowest / h * 255)
    edge[col * 4 + 1] = max(0, min(255, round(red * 255 * 1.5)))
    edge[col * 4 + 2] = 255 if lowest > h * 0.55 and rng.random() < 0.3 else 0

    x = min(w - 1, math.floor((col + 0.5) / n * w))
    ly = round(edge[col * 4] / 255 * h)
    best, best_sat = None, -1
    for yy in range(max(0, ly - 16), max(0, ly - 2) + 1):
        for xx in range(max(0, x - 3), min(w - 1, x + 3) + 1):
            r, g, b, a = pix[xx, yy]
            if a < 200:
                continue
            sat = r - max(g, b)
            if sat > best_sat:
                best_sat, best = sat, (r, g, b)
    ref = (0.33, 0.004, 0.018)
    pigment = tuple((v / 255) ** 2.2 for v in best) if best else ref
    for k in range(3):
        color[col * 4 + k] = round((ref[k] * 0.55 + pigment[k] * 0.45) * 255)
    color[col * 4 + 3] = 255
    if not best or best_sat < 70:
        edge[col * 4 + 2] = 0

out = root / 'src/scenes/logo_edges.js'
out.write_text(
    '// Generated by tools/build_logo_edges.py; 256 precomputed logo columns.\n'
    + "export const EDGE = '" + base64.b64encode(edge).decode() + "';\n"
    + "export const COLOR = '" + base64.b64encode(color).decode() + "';\n"
)
print(f'Wrote {out.relative_to(root)} ({out.stat().st_size} bytes)')
