import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true, args: ['--use-angle=metal', '--enable-gpu', '--ignore-gpu-blocklist', '--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
const errs = [];
page.on('pageerror', (e) => errs.push('pageerror: ' + e.message + ' | ' + (e.stack || '').split('\n').slice(1, 3).join(' ')));
page.on('console', (m) => { if (m.type() === 'error') errs.push('console: ' + m.text().slice(0, 200)); });
const key = async (k, wait = 250) => { await page.keyboard.press(k); await page.waitForTimeout(wait); };
const state = () => page.evaluate(() => {
  const a = window.__app;
  const vis = [...document.querySelectorAll('.menu:not(.out):not(.hidden) .item.focus .lbl')].filter((e) => e.offsetParent);
  const focus = vis.length ? vis[vis.length - 1].textContent : null;
  const menus = [...document.querySelectorAll('.menu:not(.out):not(.hidden) h2')].map((h) => h.textContent);
  return { game: a.game ? `${a.game.stageId}:${a.game.state}` : null, paused: a.paused, focus, menus, screens: [...document.querySelectorAll('.screen:not(.out)')].map((e) => e.className.replace('screen ', '')) };
});
const focusOn = async (label) => {
  for (let i = 0; i < 16; i++) { const s = await state(); if (s.focus === label) return true; await key('ArrowDown', 120); }
  console.log('!! could not focus', label); return false;
};
const step = async (label) => { const s = await state(); console.log(label.padEnd(34), JSON.stringify(s)); await page.screenshot({ path: `/tmp/flow_${label.replace(/\W+/g, '_')}.png` }); return s; };
await page.goto('http://localhost:5173/');
await page.waitForTimeout(2500);
await step('01 boot -> title');
await focusOn('OPTIONS'); await key('Enter', 500);
await step('02 options open');
await focusOn('DIFFICULTY'); await key('ArrowRight');
const diff = await page.evaluate(() => JSON.parse(localStorage.getItem('bloodbath.settings.v2') || '{}').difficulty);
console.log('   difficulty saved =', diff);
await key('ArrowLeft');
await key('Escape', 500);
await step('03 back to title');
await focusOn('CONTROLS'); await key('Enter', 500);
await step('04 controls');
await key('Escape', 400);
await focusOn('CREDITS'); await key('Enter', 400);
await step('05 credits');
await key('Escape', 400);
await focusOn('CAMPAIGN'); await key('Enter', 6000);
await step('06 campaign started');
await key('Escape', 500);
await step('07 paused');
await focusOn('OPTIONS'); await key('Enter', 500);
await step('08 pause options');
await key('Escape', 500);
await step('09 back to pause menu');
await key('Escape', 500);
await step('10 esc -> quit confirm');
await focusOn('NO, KEEP BLEEDING THEM'); await key('Enter', 500);
await step('11 no -> pause menu');
await focusOn('RESUME'); await key('Enter', 800);
await step('12 resumed');
await page.evaluate(() => { const g = window.__app.game; g.player.invuln = 0; g.player.dashT = 0; g.player.takeDamage(999, 1); });
await page.waitForTimeout(3500);
await step('13 dead -> continue prompt');
await key('Enter', 1500);
const hp = await page.evaluate(() => [window.__app.game.player.alive, Math.round(window.__app.game.player.hp)]);
console.log('   after continue alive/hp =', hp);
await page.evaluate(() => { const g = window.__app.game; g.player.invuln = 0; g.player.dashT = 0; g.player.takeDamage(999, 1); });
await page.waitForTimeout(14000);
await step('14 no continue -> game over');
await page.waitForTimeout(3000);
await step('15 results');
await focusOn('RETRY'); await key('Enter', 6000);
await step('16 retry started');
await page.evaluate(() => window.__app.game.stageClear());
await page.waitForTimeout(12000);
await step('17 clear -> results');
await focusOn('NEXT MISSION'); await key('Enter', 7000);
await step('18 next mission');
await key('Escape', 500); await key('Escape', 500); await key('Enter', 2500);
await step('19 quit to title');
await focusOn('BLOOD TIDE'); await key('Enter', 6000);
await step('20 blood tide');
await page.evaluate(() => { const g = window.__app.game; g.player.invuln = 0; g.player.takeDamage(999, 1); });
await page.waitForTimeout(6000);
await step('21 endless death -> results');
console.log(errs.length ? 'ERRORS:\n' + [...new Set(errs)].join('\n') : 'no page errors');
await browser.close();
