import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true, args: ['--use-angle=metal', '--enable-gpu', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
const errs = [];
page.on('pageerror', (e) => errs.push('pageerror: ' + e.message));
await page.addInitScript(() => {
  const pad = { id: 'fake', index: 0, connected: true, mapping: 'standard', axes: [0, 0, 0, 0], buttons: Array.from({ length: 17 }, () => ({ pressed: false, value: 0 })) };
  window.__pad = pad;
  navigator.getGamepads = () => [pad];
});
const set = (f) => page.evaluate(f);
const btn = async (i, ms = 120) => { await set(`window.__pad.buttons[${i}]={pressed:true,value:1}`); await page.waitForTimeout(ms); await set(`window.__pad.buttons[${i}]={pressed:false,value:0}`); await page.waitForTimeout(150); };
await page.goto('http://localhost:5173/');
await page.waitForTimeout(2500);
const st = () => page.evaluate(() => { const a = window.__app, g = a.game; const f = [...document.querySelectorAll('.menu:not(.out):not(.hidden) .item.focus .lbl')].filter((e) => e.offsetParent).map((e) => e.textContent); return { focus: f.pop(), game: g ? g.state : null, x: g ? +g.player.x.toFixed(2) : null, y: g ? +g.player.y.toFixed(2) : null, aim: g ? +g.player.aim.toFixed(2) : null, shots: g ? g.player.shotsFired : null, dash: g ? +g.player.dashT.toFixed(2) : null, paused: a.paused, usingPad: a.input.usingPad }; });
console.log('title', JSON.stringify(await st()));
await btn(13); console.log('dpad down', JSON.stringify(await st()));
await btn(12); console.log('dpad up', JSON.stringify(await st()));
await btn(0, 100); await page.waitForTimeout(6000);
console.log('A -> campaign', JSON.stringify(await st()));
await set('window.__pad.axes[0]=1'); await page.waitForTimeout(1200); await set('window.__pad.axes[0]=0');
console.log('stick right 1.2s', JSON.stringify(await st()));
await set('window.__pad.axes[2]=0;window.__pad.axes[3]=-1'); await page.waitForTimeout(300);
console.log('right stick up', JSON.stringify(await st()));
await set('window.__pad.buttons[7]={pressed:true,value:1}'); await page.waitForTimeout(800); await set('window.__pad.buttons[7]={pressed:false,value:0}');
console.log('RT fire 0.8s', JSON.stringify(await st()));
await set('window.__pad.axes[3]=0');
await btn(0); console.log('A jump', JSON.stringify(await st()));
await page.waitForTimeout(600);
await set('window.__pad.axes[0]=1'); await btn(1, 60); console.log('B dash', JSON.stringify(await st())); await set('window.__pad.axes[0]=0');
await btn(9); console.log('start pause', JSON.stringify(await st()));
await btn(13); await btn(0); console.log('pause: A on 2nd item', JSON.stringify(await st()));
await page.waitForTimeout(500);
console.log(errs.length ? errs.join('\n') : 'no page errors');
await browser.close();
