import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true, args: ['--use-angle=metal', '--enable-gpu', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
const errs = []; page.on('pageerror', (e) => errs.push(e.message));
await page.goto('http://localhost:5173/');
await page.evaluate(() => localStorage.removeItem('bloodbath.records.v1'));
await page.reload(); await page.waitForTimeout(2500);
const items = () => page.evaluate(() => [...document.querySelectorAll('.title-menu .item')].map((e) => e.querySelector('.lbl').textContent + (e.classList.contains('disabled') ? '(locked)' : '')));
console.log('fresh:', (await items()).join(' | '));
await page.evaluate(() => window.__app.startStage('stage1', null)); await page.waitForTimeout(5000);
await page.evaluate(() => window.__app.game.stageClear()); await page.waitForTimeout(9000);
await page.evaluate(() => window.__app.toTitle()); await page.waitForTimeout(1500);
console.log('after stage1 clear:', (await items()).join(' | '));
await page.evaluate(() => window.__app.startStage('boss', null)); await page.waitForTimeout(5000);
await page.evaluate(() => window.__app.game.stageClear()); await page.waitForTimeout(9000);
const res = await page.evaluate(() => [...document.querySelectorAll('.res-menu .item .lbl')].map((e) => e.textContent));
console.log('after boss results menu:', res.join(' | '));
await page.evaluate(() => [...document.querySelectorAll('.res-menu .item')].find((e) => e.textContent.includes('CREDITS')).click());
await page.waitForTimeout(1500);
console.log('credits open:', await page.evaluate(() => [...document.querySelectorAll('.menu h2')].map((h) => h.textContent)));
await page.keyboard.press('Escape'); await page.waitForTimeout(800);
console.log('mission select:', await page.evaluate(() => { const b = [...document.querySelectorAll('.title-menu .item')].find((e) => e.textContent.includes('MISSION')); b.click(); return 1; }));
await page.waitForTimeout(600);
console.log('missions:', (await page.evaluate(() => [...document.querySelectorAll('.overlay .item')].map((e) => e.querySelector('.lbl').textContent + (e.classList.contains('disabled') ? '(locked)' : '') + ' ' + e.querySelector('.val').textContent))).join(' | '));
console.log(errs.length ? errs.join('\n') : 'no page errors');
await browser.close();
